//5 productMaterial objects in setKnownGoodState

// Find all ProductMaterial objects for product 1; should give 200
GET /api/productMaterial/1 HTTP/1.1 
Host: localhost:8080

###

// Add a ProductMaterial; should give 201 & show productMaterial for materialId: 1
POST /api/productMaterial HTTP/1.1 
Host: localhost:8080 
Content-Type: application/json 

{
    "materialQuantity": 16,
    "productId": 1,
    "material" : {
        "materialId": 1
    }
} 

### 


// Try to add a duplicate productMaterial 
// Should give 400 with "Product already is linked to this material." message
POST /api/productMaterial HTTP/1.1 
Host: localhost:8080 
Content-Type: application/json 

{
    "materialQuantity": 16,
    "productId": 1,
    "material" : {
        "materialId": 1
    }
} 
###  


// Update the productMaterial  
// Should give 204
PUT /api/productMaterial/1/1 HTTP/1.1 
Host: localhost:8080 
Content-Type: application/json 

{
    "materialQuantity": 20,
    "productId": 1,
    "material" : {
        "materialId": 1
    }
} 

### 

// View updated quantity for material 1
GET /api/productMaterial/1 HTTP/1.1 
Host: localhost:8080

###


// Delete By Id; should give 204 the first time, 404 after
DELETE /api/productMaterial/1/1 HTTP/1.1 
Host: localhost:8080
### 
