//2 users in setKnownGoodState, all with inventory objects

// Find All users; 200 & show users 'username' and 'test' with materials and products
//does not show materials or products
GET /api/user HTTP/1.1 
Host: localhost:8080 
### 


// Find user By ID; should give 200 & show user 'username' with materials and products
//currently shows materials and products
GET /api/user/username HTTP/1.1 
Host: localhost:8080 
###  

// Should not find this user; should show 200 with an empty response
GET /api/user/fakeuser HTTP/1.1 
Host: localhost:8080 

###  

// Add a user; should give 201 & show newUser
POST /api/user HTTP/1.1 
Host: localhost:8080 
Content-Type: application/json 

{
    "userId": "newUser"
} 

###  


// Attempt to add same user; should give 400
POST /api/user HTTP/1.1 
Host: localhost:8080 
Content-Type: application/json 

{
    "userId": "newUser"
} 


### 

// View newUse; should give 200 & show newUser
GET /api/user/newUser HTTP/1.1 
Host: localhost:8080 

###